### ISSUE TITLE
What's `Godot-Request-ID` in response?

### ISSUE THREAD

**Issue by uiosun** [tony709394/Hey#1]
Request header can't hold to reponse, this is a bug or specific functional?

**Comment by tony709394** [comment]
> 

`Godot-Request-ID` is a `HTTPRequest` ID that is used for GC. I think there's something wrong with your config params.

**Comment by uiosun** [comment]
How to find the right config? I not got any message by there question from google search.

Ps: Tony 是理发师 Tony？

**Comment by tony709394** [comment]
> 

是不是没有按照 README 里面的案例代码运行... gogo、tony、jenny 里面的 tony

**Comment by uiosun** [comment]
我注意到这里有 ”3.0+“ 的标识，这是指 3.0.* 吗？

我目前用的是 Steam 自动更新的 v3.4.2.stable.official [45eaa2daf]，在这个版本下，README 的代码无效，它抛出了一模一样的错误。

---

I find "3.0+" version limit in README.md, the mean is 3.0.*?

I use Godot from Steam, it can auto upgrade Godot, now is v3.4.2 (stable).

use README.md example code, failed show again.

Ps: 查了一下，GOGO学英语，似乎小时候听过这个名字。很陌生哈哈，看来是童年错过

**Comment by tony709394** [comment]
> 我注意到这里有 ”3.0+“ 的标识，这是指 3.0.* 吗？
> 
> 我目前用的是 Steam 自动更新的 v3.4.2.stable.official [45eaa2daf]，在这个版本下，README 的代码无效，它抛出了一模一样的错误。
> 
> I find "3.0+" version limit in README.md, the mean is 3.0.*?
> 
> I use Godot from Steam, it can auto upgrade Godot, now is v3.4.2 (stable).
> 
> use README.md example code, failed show again.
> 
> Ps: 查了一下，GOGO学英语，似乎小时候听过这个名字。很陌生哈哈，看来是童年错过

可以简单发一下相关代码，以及报错吗？

**Comment by uiosun** [comment]
Demo 文件夹里的项目可以直接测，错误：

`Invalid get index '1' (on base: 'PoolStringArray')`

`print(headers[0].split("Godot-Request-ID:"))` 日志：

```
--- Debugging process started ---
Godot Engine v3.4.2.stable.official.45eaa2daf - https://godotengine.org
OpenGL ES 2.0 Renderer: NVIDIA GeForce GTX 1060/PCIe/SSE2
OpenGL ES Batching: ON
 
[Content-Type: application/json; charset=UTF-8]
```

**Comment by tony709394** [comment]
> 

我想起来了，之前利用 godot 请求回调的漏洞（headers参数返回 不是响应头，而是请求头）。
但是，新版本修复了这个漏洞，导致无法用自定义请求头，跟踪请求了... 我试试其他跟踪方案吧

**Comment by tony709394** [comment]
> Demo 文件夹里的项目可以直接测，错误：
> 
> `Invalid get index '1' (on base: 'PoolStringArray')`
> 
> `print(headers[0].split("Godot-Request-ID:"))` 日志：
> 
> ```
> --- Debugging process started ---
> Godot Engine v3.4.2.stable.official.45eaa2daf - https://godotengine.org
> OpenGL ES 2.0 Renderer: NVIDIA GeForce GTX 1060/PCIe/SSE2
> OpenGL ES Batching: ON
>  
> [Content-Type: application/json; charset=UTF-8]
> ```

我想起来了，之前利用 godot 请求回调的漏洞（headers参数返回 不是响应头，而是请求头）。
但是，新版本修复了这个漏洞，导致无法用自定义请求头，跟踪请求了... 我试试其他跟踪方案吧

**Comment by tony709394** [comment]
跟踪问题修复后，我关闭 issue

**Comment by tony709394** [comment]
等待官方完成 `HTTPRequest` 相关提案 [3946](https://github.com/godotengine/godot-proposals/issues/3946) 后，我再跟进这个问题。
问题解决后，我关闭这个 `issue`。

**Comment by uiosun** [comment]
好，等待中

**Comment by tony709394** [comment]
In the newest version, the trace request issue has been fixed.
